name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  REPO_NAME: salesforce/phoenix-mini

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven package
        run: mvn --batch-mode package
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.DOCKER_REGISTRY }}
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Push
        if: github.ref == 'refs/heads/master'
        run: |
          REMOTE_IMAGE_ID=$DOCKER_REGISTRY/$REPO_NAME:latest
          docker tag phoenix-mini:latest $REMOTE_IMAGE_ID
          docker push $REMOTE_IMAGE_ID